import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MobileSidebar } from "@/components/MobileSidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <div className="flex min-h-screen">
          {/* Desktop Sidebar - hidden on mobile */}
          <aside className="hidden md:flex w-56 bg-card border-r border-border shadow-sm flex-col">
            <div className="font-bold text-lg p-4 border-b border-border">Chat App</div>
            <nav className="flex-1 flex flex-col gap-2 p-4">
              <a href="/" className="px-3 py-2 rounded hover:bg-muted transition">Chat</a>
              <a href="/gallery" className="px-3 py-2 rounded hover:bg-muted transition">Gallery</a>
              <a href="/upload" className="px-3 py-2 rounded hover:bg-muted transition">Upload</a>
            </nav>
          </aside>
          <div className="flex-1 flex flex-col">
            {/* Mobile Header with Sidebar Button */}
            <header className="md:hidden flex items-center p-4 border-b border-border bg-card">
              <MobileSidebar />
              <div className="font-bold text-lg ml-3">Chat App</div>
            </header>
            <main className="flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
